#include <futurepia/protocol/get_config.hpp>
#include <futurepia/protocol/config.hpp>
#include <futurepia/protocol/asset.hpp>
#include <futurepia/protocol/types.hpp>
#include <futurepia/protocol/version.hpp>

namespace futurepia { namespace protocol {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

   result[ "IS_TEST_NET" ] = true;
   result["SNAC_SYMBOL"] = SNAC_SYMBOL;
   result["FUTUREPIA_100_PERCENT"] = FUTUREPIA_100_PERCENT;
   result["FUTUREPIA_1_PERCENT"] = FUTUREPIA_1_PERCENT;
   result["FUTUREPIA_1_TENTH_PERCENT"] = FUTUREPIA_1_TENTH_PERCENT;
   result["FUTUREPIA_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = FUTUREPIA_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
   result["FUTUREPIA_ADDRESS_PREFIX"] = FUTUREPIA_ADDRESS_PREFIX;
   result["FUTUREPIA_BLOCKCHAIN_PRECISION_DIGITS"] = FUTUREPIA_BLOCKCHAIN_PRECISION_DIGITS;
   result["FUTUREPIA_BLOCKCHAIN_SNAC_PRECISION_DIGITS"] = FUTUREPIA_BLOCKCHAIN_SNAC_PRECISION_DIGITS;
   result["FUTUREPIA_BLOCKCHAIN_HARDFORK_VERSION"] = FUTUREPIA_BLOCKCHAIN_HARDFORK_VERSION;
   result["FUTUREPIA_BLOCKCHAIN_VERSION"] = FUTUREPIA_BLOCKCHAIN_VERSION;
   result["FUTUREPIA_BLOCK_INTERVAL"] = FUTUREPIA_BLOCK_INTERVAL;
   result["FUTUREPIA_BLOCKS_PER_DAY"] = FUTUREPIA_BLOCKS_PER_DAY;
   result["FUTUREPIA_BLOCKS_PER_YEAR"] = FUTUREPIA_BLOCKS_PER_YEAR;
   result["FUTUREPIA_CHAIN_ID"] = FUTUREPIA_CHAIN_ID;
   result["FUTUREPIA_CREATE_ACCOUNT_DELEGATION_RATIO"] = FUTUREPIA_CREATE_ACCOUNT_DELEGATION_RATIO;
   result["FUTUREPIA_CREATE_ACCOUNT_WITH_FUTUREPIA_MODIFIER"] = FUTUREPIA_CREATE_ACCOUNT_WITH_FUTUREPIA_MODIFIER;
   result["FUTUREPIA_GENESIS_TIME"] = FUTUREPIA_GENESIS_TIME;
   result["FUTUREPIA_HARDFORK_REQUIRED_BOBSERVERS"] = FUTUREPIA_HARDFORK_REQUIRED_BOBSERVERS;
   result["FUTUREPIA_INIT_MINER_NAME"] = FUTUREPIA_INIT_MINER_NAME;
   result["FUTUREPIA_INIT_PUBLIC_KEY_STR"] = FUTUREPIA_INIT_PUBLIC_KEY_STR;
   result["FUTUREPIA_INIT_PRIVATE_KEY"] = FUTUREPIA_INIT_PRIVATE_KEY;
   result["FUTUREPIA_INIT_SUPPLY"] = FUTUREPIA_INIT_SUPPLY;
   result["FUTUREPIA_INIT_TIME"] = FUTUREPIA_INIT_TIME;
   result["FUTUREPIA_IRREVERSIBLE_THRESHOLD"] = FUTUREPIA_IRREVERSIBLE_THRESHOLD;
   result["FUTUREPIA_MAX_ACCOUNT_NAME_LENGTH"] = FUTUREPIA_MAX_ACCOUNT_NAME_LENGTH;
   result["FUTUREPIA_MAX_ACCOUNT_BOBSERVER_VOTES"] = FUTUREPIA_MAX_ACCOUNT_BOBSERVER_VOTES;
   result["FUTUREPIA_MAX_BLOCK_SIZE"] = FUTUREPIA_MAX_BLOCK_SIZE;
   result["FUTUREPIA_MAX_COMMENT_DEPTH"] = FUTUREPIA_MAX_COMMENT_DEPTH;
   result["FUTUREPIA_MAX_MEMO_SIZE"] = FUTUREPIA_MAX_MEMO_SIZE;
   result["FUTUREPIA_MAX_BOBSERVERS"] = FUTUREPIA_MAX_BOBSERVERS;
   result["FUTUREPIA_MAX_MINER_BOBSERVERS_HF0"] = FUTUREPIA_MAX_MINER_BOBSERVERS_HF0;
   result["FUTUREPIA_MAX_PERMLINK_LENGTH"] = FUTUREPIA_MAX_PERMLINK_LENGTH;
   result["FUTUREPIA_MAX_RESERVE_RATIO"] = FUTUREPIA_MAX_RESERVE_RATIO;
   result["FUTUREPIA_MAX_RUNNER_BOBSERVERS_HF0"] = FUTUREPIA_MAX_RUNNER_BOBSERVERS_HF0;
   result["FUTUREPIA_MAX_SHARE_SUPPLY"] = FUTUREPIA_MAX_SHARE_SUPPLY;
   result["FUTUREPIA_MAX_SIG_CHECK_DEPTH"] = FUTUREPIA_MAX_SIG_CHECK_DEPTH;
   result["FUTUREPIA_MAX_TIME_UNTIL_EXPIRATION"] = FUTUREPIA_MAX_TIME_UNTIL_EXPIRATION;
   result["FUTUREPIA_MAX_TRANSACTION_SIZE"] = FUTUREPIA_MAX_TRANSACTION_SIZE;
   result["FUTUREPIA_MAX_UNDO_HISTORY"] = FUTUREPIA_MAX_UNDO_HISTORY;
   result["FUTUREPIA_MAX_VOTED_BOBSERVERS_HF0"] = FUTUREPIA_MAX_VOTED_BOBSERVERS_HF0;
   result["FUTUREPIA_MAX_BOBSERVER_URL_LENGTH"] = FUTUREPIA_MAX_BOBSERVER_URL_LENGTH;
   result["FUTUREPIA_MIN_ACCOUNT_NAME_LENGTH"] = FUTUREPIA_MIN_ACCOUNT_NAME_LENGTH;
   result["FUTUREPIA_MIN_BLOCK_SIZE"] = FUTUREPIA_MIN_BLOCK_SIZE;
   result["FUTUREPIA_MIN_BLOCK_SIZE_LIMIT"] = FUTUREPIA_MIN_BLOCK_SIZE_LIMIT;
   result["FUTUREPIA_MIN_PERMLINK_LENGTH"] = FUTUREPIA_MIN_PERMLINK_LENGTH;
   result["FUTUREPIA_MIN_REPLY_INTERVAL"] = FUTUREPIA_MIN_REPLY_INTERVAL;
   result["FUTUREPIA_MIN_ROOT_COMMENT_INTERVAL"] = FUTUREPIA_MIN_ROOT_COMMENT_INTERVAL;
   result["FUTUREPIA_MIN_VOTE_INTERVAL_SEC"] = FUTUREPIA_MIN_VOTE_INTERVAL_SEC;
   result["FUTUREPIA_MINER_ACCOUNT"] = FUTUREPIA_MINER_ACCOUNT;
   result["FUTUREPIA_MINING_TIME"] = FUTUREPIA_MINING_TIME;
   result["FUTUREPIA_MIN_UNDO_HISTORY"] = FUTUREPIA_MIN_UNDO_HISTORY;
   result["FUTUREPIA_NULL_ACCOUNT"] = FUTUREPIA_NULL_ACCOUNT;
   result["FUTUREPIA_NUM_INIT_MINERS"] = FUTUREPIA_NUM_INIT_MINERS;
   result["FUTUREPIA_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = FUTUREPIA_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
   result["FUTUREPIA_OWNER_AUTH_RECOVERY_PERIOD"] = FUTUREPIA_OWNER_AUTH_RECOVERY_PERIOD;
   result["FUTUREPIA_OWNER_UPDATE_LIMIT"] = FUTUREPIA_OWNER_UPDATE_LIMIT;
   result["FUTUREPIA_ROOT_POST_PARENT"] = FUTUREPIA_ROOT_POST_PARENT;
   result["FUTUREPIA_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = FUTUREPIA_SAVINGS_WITHDRAW_REQUEST_LIMIT;
   result["FUTUREPIA_SOFT_MAX_COMMENT_DEPTH"] = FUTUREPIA_SOFT_MAX_COMMENT_DEPTH;
   result["FUTUREPIA_START_MINER_VOTING_BLOCK"] = FUTUREPIA_START_MINER_VOTING_BLOCK;
   result["PIA_SYMBOL"] = PIA_SYMBOL;
   result["FUTUREPIA_TEMP_ACCOUNT"] = FUTUREPIA_TEMP_ACCOUNT;
   result["FUTUREPIA_TRANSFER_SAVINGS_MAX_MONTH"] = FUTUREPIA_TRANSFER_SAVINGS_MAX_MONTH;
   result["FUTUREPIA_TRANSFER_SAVINGS_CYCLE"] = FUTUREPIA_TRANSFER_SAVINGS_CYCLE;
   result["FUTUREPIA_DEPOSIT_FUND_NAME"] = FUTUREPIA_DEPOSIT_FUND_NAME;
   result["FUTUREPIA_DEPOSIT_COUNT_LIMIT"] = FUTUREPIA_DEPOSIT_COUNT_LIMIT;
   result["FUTUREPIA_EXCHANGE_MIN_BALANCE "] = FUTUREPIA_EXCHANGE_MIN_BALANCE;
   result["FUTUREPIA_EXCHANGE_FEE "] = FUTUREPIA_EXCHANGE_FEE;
   result["FUTUREPIA_EXCHANGE_FEE_OWNER"] = FUTUREPIA_EXCHANGE_FEE_OWNER;
   result["FUTUREPIA_DAPP_TRANSACTION_FEE"] = FUTUREPIA_DAPP_TRANSACTION_FEE;

   return result;
}

} } // futurepia::protocol
