#include <futurepia/protocol/get_config.hpp>
#include <futurepia/protocol/config.hpp>
#include <futurepia/protocol/asset.hpp>
#include <futurepia/protocol/types.hpp>
#include <futurepia/protocol/version.hpp>

namespace futurepia { namespace protocol {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

#ifdef IS_TEST_NET
   result[ "IS_TEST_NET" ] = true;
#else
   result[ "IS_TEST_NET" ] = false;
#endif

   result["FPCH_SYMBOL"] = FPCH_SYMBOL;
   result["FUTUREPIA_100_PERCENT"] = FUTUREPIA_100_PERCENT;
   result["FUTUREPIA_1_PERCENT"] = FUTUREPIA_1_PERCENT;
   result["FUTUREPIA_1_TENTH_PERCENT"] = FUTUREPIA_1_TENTH_PERCENT;
   result["FUTUREPIA_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = FUTUREPIA_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
   result["FUTUREPIA_ACTIVE_CHALLENGE_COOLDOWN"] = FUTUREPIA_ACTIVE_CHALLENGE_COOLDOWN;
   result["FUTUREPIA_ACTIVE_CHALLENGE_FEE"] = FUTUREPIA_ACTIVE_CHALLENGE_FEE;
   result["FUTUREPIA_ADDRESS_PREFIX"] = FUTUREPIA_ADDRESS_PREFIX;
   result["FUTUREPIA_APR_PERCENT_MULTIPLY_PER_BLOCK"] = FUTUREPIA_APR_PERCENT_MULTIPLY_PER_BLOCK;
   result["FUTUREPIA_APR_PERCENT_MULTIPLY_PER_HOUR"] = FUTUREPIA_APR_PERCENT_MULTIPLY_PER_HOUR;
   result["FUTUREPIA_APR_PERCENT_MULTIPLY_PER_ROUND"] = FUTUREPIA_APR_PERCENT_MULTIPLY_PER_ROUND;
   result["FUTUREPIA_APR_PERCENT_SHIFT_PER_BLOCK"] = FUTUREPIA_APR_PERCENT_SHIFT_PER_BLOCK;
   result["FUTUREPIA_APR_PERCENT_SHIFT_PER_HOUR"] = FUTUREPIA_APR_PERCENT_SHIFT_PER_HOUR;
   result["FUTUREPIA_APR_PERCENT_SHIFT_PER_ROUND"] = FUTUREPIA_APR_PERCENT_SHIFT_PER_ROUND;
   result["FUTUREPIA_BANDWIDTH_AVERAGE_WINDOW_SECONDS"] = FUTUREPIA_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
   result["FUTUREPIA_BANDWIDTH_PRECISION"] = FUTUREPIA_BANDWIDTH_PRECISION;
   result["FUTUREPIA_BLOCKCHAIN_PRECISION"] = FUTUREPIA_BLOCKCHAIN_PRECISION;
   result["FUTUREPIA_BLOCKCHAIN_PRECISION_DIGITS"] = FUTUREPIA_BLOCKCHAIN_PRECISION_DIGITS;
   result["FUTUREPIA_BLOCKCHAIN_HARDFORK_VERSION"] = FUTUREPIA_BLOCKCHAIN_HARDFORK_VERSION;
   result["FUTUREPIA_BLOCKCHAIN_VERSION"] = FUTUREPIA_BLOCKCHAIN_VERSION;
   result["FUTUREPIA_BLOCK_INTERVAL"] = FUTUREPIA_BLOCK_INTERVAL;
   result["FUTUREPIA_BLOCKS_PER_DAY"] = FUTUREPIA_BLOCKS_PER_DAY;
   result["FUTUREPIA_BLOCKS_PER_HOUR"] = FUTUREPIA_BLOCKS_PER_HOUR;
   result["FUTUREPIA_BLOCKS_PER_YEAR"] = FUTUREPIA_BLOCKS_PER_YEAR;
   result["FUTUREPIA_CASHOUT_WINDOW_SECONDS"] = FUTUREPIA_CASHOUT_WINDOW_SECONDS;
   result["FUTUREPIA_CASHOUT_WINDOW_SECONDS_PRE_HF12"] = FUTUREPIA_CASHOUT_WINDOW_SECONDS_PRE_HF12;
   result["FUTUREPIA_CASHOUT_WINDOW_SECONDS_PRE_HF17"] = FUTUREPIA_CASHOUT_WINDOW_SECONDS_PRE_HF17;
   result["FUTUREPIA_CHAIN_ID"] = FUTUREPIA_CHAIN_ID;
   result["FUTUREPIA_COMMENT_REWARD_FUND_NAME"] = FUTUREPIA_COMMENT_REWARD_FUND_NAME;
   result["FUTUREPIA_CONTENT_APR_PERCENT"] = FUTUREPIA_CONTENT_APR_PERCENT;
   result["FUTUREPIA_CONTENT_CONSTANT_HF0"] = FUTUREPIA_CONTENT_CONSTANT_HF0;
   result["FUTUREPIA_CONTENT_REWARD_PERCENT"] = FUTUREPIA_CONTENT_REWARD_PERCENT;
   result["FUTUREPIA_CONVERSION_DELAY"] = FUTUREPIA_CONVERSION_DELAY;
   result["FUTUREPIA_CONVERSION_DELAY_PRE_HF_16"] = FUTUREPIA_CONVERSION_DELAY_PRE_HF_16;
   result["FUTUREPIA_CREATE_ACCOUNT_DELEGATION_RATIO"] = FUTUREPIA_CREATE_ACCOUNT_DELEGATION_RATIO;
   result["FUTUREPIA_CREATE_ACCOUNT_DELEGATION_TIME"] = FUTUREPIA_CREATE_ACCOUNT_DELEGATION_TIME;
   result["FUTUREPIA_CREATE_ACCOUNT_WITH_FUTUREPIA_MODIFIER"] = FUTUREPIA_CREATE_ACCOUNT_WITH_FUTUREPIA_MODIFIER;
   result["FUTUREPIA_CURATE_APR_PERCENT"] = FUTUREPIA_CURATE_APR_PERCENT;
   result["FUTUREPIA_DEFAULT_FPCH_INTEREST_RATE"] = FUTUREPIA_DEFAULT_FPCH_INTEREST_RATE;
   result["FUTUREPIA_EQUIHASH_K"] = FUTUREPIA_EQUIHASH_K;
   result["FUTUREPIA_EQUIHASH_N"] = FUTUREPIA_EQUIHASH_N;
   result["FUTUREPIA_FEED_HISTORY_WINDOW"] = FUTUREPIA_FEED_HISTORY_WINDOW;
   result["FUTUREPIA_FEED_HISTORY_WINDOW_PRE_HF_16"] = FUTUREPIA_FEED_HISTORY_WINDOW_PRE_HF_16;
   result["FUTUREPIA_FEED_INTERVAL_BLOCKS"] = FUTUREPIA_FEED_INTERVAL_BLOCKS;
   result["FUTUREPIA_FREE_TRANSACTIONS_WITH_NEW_ACCOUNT"] = FUTUREPIA_FREE_TRANSACTIONS_WITH_NEW_ACCOUNT;
   result["FUTUREPIA_GENESIS_TIME"] = FUTUREPIA_GENESIS_TIME;
   result["FUTUREPIA_HARDFORK_REQUIRED_BOBSERVERS"] = FUTUREPIA_HARDFORK_REQUIRED_BOBSERVERS;
   result["FUTUREPIA_INFLATION_NARROWING_PERIOD"] = FUTUREPIA_INFLATION_NARROWING_PERIOD;
   result["FUTUREPIA_INFLATION_RATE_START_PERCENT"] = FUTUREPIA_INFLATION_RATE_START_PERCENT;
   result["FUTUREPIA_INFLATION_RATE_STOP_PERCENT"] = FUTUREPIA_INFLATION_RATE_STOP_PERCENT;
   result["FUTUREPIA_INIT_MINER_NAME"] = FUTUREPIA_INIT_MINER_NAME;
   result["FUTUREPIA_INIT_PUBLIC_KEY_STR"] = FUTUREPIA_INIT_PUBLIC_KEY_STR;
#if 0
   // do not expose private key, period.
   // we need this line present but inactivated so CI check for all constants in config.hpp doesn't complain.
   result["FUTUREPIA_INIT_PRIVATE_KEY"] = FUTUREPIA_INIT_PRIVATE_KEY;
#endif
   result["FUTUREPIA_INIT_SUPPLY"] = FUTUREPIA_INIT_SUPPLY;
   result["FUTUREPIA_INIT_TIME"] = FUTUREPIA_INIT_TIME;
   result["FUTUREPIA_IRREVERSIBLE_THRESHOLD"] = FUTUREPIA_IRREVERSIBLE_THRESHOLD;
   result["FUTUREPIA_LIQUIDITY_APR_PERCENT"] = FUTUREPIA_LIQUIDITY_APR_PERCENT;
   result["FUTUREPIA_LIQUIDITY_REWARD_BLOCKS"] = FUTUREPIA_LIQUIDITY_REWARD_BLOCKS;
   result["FUTUREPIA_LIQUIDITY_REWARD_PERIOD_SEC"] = FUTUREPIA_LIQUIDITY_REWARD_PERIOD_SEC;
   result["FUTUREPIA_LIQUIDITY_TIMEOUT_SEC"] = FUTUREPIA_LIQUIDITY_TIMEOUT_SEC;
   result["FUTUREPIA_MAX_ACCOUNT_NAME_LENGTH"] = FUTUREPIA_MAX_ACCOUNT_NAME_LENGTH;
   result["FUTUREPIA_MAX_ACCOUNT_BOBSERVER_VOTES"] = FUTUREPIA_MAX_ACCOUNT_BOBSERVER_VOTES;
   result["FUTUREPIA_MAX_ASSET_WHITELIST_AUTHORITIES"] = FUTUREPIA_MAX_ASSET_WHITELIST_AUTHORITIES;
   result["FUTUREPIA_MAX_AUTHORITY_MEMBERSHIP"] = FUTUREPIA_MAX_AUTHORITY_MEMBERSHIP;
   result["FUTUREPIA_MAX_BLOCK_SIZE"] = FUTUREPIA_MAX_BLOCK_SIZE;
   result["FUTUREPIA_MAX_COMMENT_DEPTH"] = FUTUREPIA_MAX_COMMENT_DEPTH;
   result["FUTUREPIA_MAX_COMMENT_DEPTH_PRE_HF17"] = FUTUREPIA_MAX_COMMENT_DEPTH_PRE_HF17;
   result["FUTUREPIA_MAX_FEED_AGE_SECONDS"] = FUTUREPIA_MAX_FEED_AGE_SECONDS;
   result["FUTUREPIA_MAX_INSTANCE_ID"] = FUTUREPIA_MAX_INSTANCE_ID;
   result["FUTUREPIA_MAX_MEMO_SIZE"] = FUTUREPIA_MAX_MEMO_SIZE;
   result["FUTUREPIA_MAX_BOBSERVERS"] = FUTUREPIA_MAX_BOBSERVERS;
   result["FUTUREPIA_MAX_MINER_BOBSERVERS_HF0"] = FUTUREPIA_MAX_MINER_BOBSERVERS_HF0;
   result["FUTUREPIA_MAX_PERMLINK_LENGTH"] = FUTUREPIA_MAX_PERMLINK_LENGTH;
   result["FUTUREPIA_MAX_PROXY_RECURSION_DEPTH"] = FUTUREPIA_MAX_PROXY_RECURSION_DEPTH;
   result["FUTUREPIA_MAX_RATION_DECAY_RATE"] = FUTUREPIA_MAX_RATION_DECAY_RATE;
   result["FUTUREPIA_MAX_RESERVE_RATIO"] = FUTUREPIA_MAX_RESERVE_RATIO;
   result["FUTUREPIA_MAX_RUNNER_BOBSERVERS_HF0"] = FUTUREPIA_MAX_RUNNER_BOBSERVERS_HF0;
   result["FUTUREPIA_MAX_SHARE_SUPPLY"] = FUTUREPIA_MAX_SHARE_SUPPLY;
   result["FUTUREPIA_MAX_SIG_CHECK_DEPTH"] = FUTUREPIA_MAX_SIG_CHECK_DEPTH;
   result["FUTUREPIA_MAX_TIME_UNTIL_EXPIRATION"] = FUTUREPIA_MAX_TIME_UNTIL_EXPIRATION;
   result["FUTUREPIA_MAX_TRANSACTION_SIZE"] = FUTUREPIA_MAX_TRANSACTION_SIZE;
   result["FUTUREPIA_MAX_UNDO_HISTORY"] = FUTUREPIA_MAX_UNDO_HISTORY;
   result["FUTUREPIA_MAX_URL_LENGTH"] = FUTUREPIA_MAX_URL_LENGTH;
   result["FUTUREPIA_MAX_VOTE_CHANGES"] = FUTUREPIA_MAX_VOTE_CHANGES;
   result["FUTUREPIA_MAX_VOTED_BOBSERVERS_HF0"] = FUTUREPIA_MAX_VOTED_BOBSERVERS_HF0;
   result["FUTUREPIA_MAX_BOBSERVER_URL_LENGTH"] = FUTUREPIA_MAX_BOBSERVER_URL_LENGTH;
   result["FUTUREPIA_MIN_ACCOUNT_CREATION_FEE"] = FUTUREPIA_MIN_ACCOUNT_CREATION_FEE;
   result["FUTUREPIA_MIN_ACCOUNT_NAME_LENGTH"] = FUTUREPIA_MIN_ACCOUNT_NAME_LENGTH;
   result["FUTUREPIA_MIN_BLOCK_SIZE"] = FUTUREPIA_MIN_BLOCK_SIZE;
   result["FUTUREPIA_MIN_BLOCK_SIZE_LIMIT"] = FUTUREPIA_MIN_BLOCK_SIZE_LIMIT;
   result["FUTUREPIA_MIN_CONTENT_REWARD"] = FUTUREPIA_MIN_CONTENT_REWARD;
   result["FUTUREPIA_MIN_CURATE_REWARD"] = FUTUREPIA_MIN_CURATE_REWARD;
   result["FUTUREPIA_MIN_PERMLINK_LENGTH"] = FUTUREPIA_MIN_PERMLINK_LENGTH;
   result["FUTUREPIA_MIN_REPLY_INTERVAL"] = FUTUREPIA_MIN_REPLY_INTERVAL;
   result["FUTUREPIA_MIN_ROOT_COMMENT_INTERVAL"] = FUTUREPIA_MIN_ROOT_COMMENT_INTERVAL;
   result["FUTUREPIA_MIN_VOTE_INTERVAL_SEC"] = FUTUREPIA_MIN_VOTE_INTERVAL_SEC;
   result["FUTUREPIA_MINER_ACCOUNT"] = FUTUREPIA_MINER_ACCOUNT;
   result["FUTUREPIA_MINER_PAY_PERCENT"] = FUTUREPIA_MINER_PAY_PERCENT;
   result["FUTUREPIA_MIN_FEEDS"] = FUTUREPIA_MIN_FEEDS;
   result["FUTUREPIA_MINING_REWARD"] = FUTUREPIA_MINING_REWARD;
   result["FUTUREPIA_MINING_TIME"] = FUTUREPIA_MINING_TIME;
   result["FUTUREPIA_MIN_LIQUIDITY_REWARD"] = FUTUREPIA_MIN_LIQUIDITY_REWARD;
   result["FUTUREPIA_MIN_LIQUIDITY_REWARD_PERIOD_SEC"] = FUTUREPIA_MIN_LIQUIDITY_REWARD_PERIOD_SEC;
   result["FUTUREPIA_MIN_PAYOUT_FPCH"] = FUTUREPIA_MIN_PAYOUT_FPCH;
   result["FUTUREPIA_MIN_POW_REWARD"] = FUTUREPIA_MIN_POW_REWARD;
   result["FUTUREPIA_MIN_PRODUCER_REWARD"] = FUTUREPIA_MIN_PRODUCER_REWARD;
   result["FUTUREPIA_MIN_RATION"] = FUTUREPIA_MIN_RATION;
   result["FUTUREPIA_MIN_TRANSACTION_EXPIRATION_LIMIT"] = FUTUREPIA_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result["FUTUREPIA_MIN_TRANSACTION_SIZE_LIMIT"] = FUTUREPIA_MIN_TRANSACTION_SIZE_LIMIT;
   result["FUTUREPIA_MIN_UNDO_HISTORY"] = FUTUREPIA_MIN_UNDO_HISTORY;
   result["FUTUREPIA_NULL_ACCOUNT"] = FUTUREPIA_NULL_ACCOUNT;
   result["FUTUREPIA_NUM_INIT_MINERS"] = FUTUREPIA_NUM_INIT_MINERS;
   result["FUTUREPIA_ORIGINAL_MIN_ACCOUNT_CREATION_FEE"] = FUTUREPIA_ORIGINAL_MIN_ACCOUNT_CREATION_FEE;
   result["FUTUREPIA_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = FUTUREPIA_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
   result["FUTUREPIA_OWNER_AUTH_RECOVERY_PERIOD"] = FUTUREPIA_OWNER_AUTH_RECOVERY_PERIOD;
   result["FUTUREPIA_OWNER_CHALLENGE_COOLDOWN"] = FUTUREPIA_OWNER_CHALLENGE_COOLDOWN;
   result["FUTUREPIA_OWNER_CHALLENGE_FEE"] = FUTUREPIA_OWNER_CHALLENGE_FEE;
   result["FUTUREPIA_OWNER_UPDATE_LIMIT"] = FUTUREPIA_OWNER_UPDATE_LIMIT;
   result["FUTUREPIA_POST_AVERAGE_WINDOW"] = FUTUREPIA_POST_AVERAGE_WINDOW;
   result["FUTUREPIA_POST_MAX_BANDWIDTH"] = FUTUREPIA_POST_MAX_BANDWIDTH;
   result["FUTUREPIA_POST_REWARD_FUND_NAME"] = FUTUREPIA_POST_REWARD_FUND_NAME;
   result["FUTUREPIA_POST_WEIGHT_CONSTANT"] = FUTUREPIA_POST_WEIGHT_CONSTANT;
   result["FUTUREPIA_POW_APR_PERCENT"] = FUTUREPIA_POW_APR_PERCENT;
   result["FUTUREPIA_PRODUCER_APR_PERCENT"] = FUTUREPIA_PRODUCER_APR_PERCENT;
   result["FUTUREPIA_PROXY_TO_SELF_ACCOUNT"] = FUTUREPIA_PROXY_TO_SELF_ACCOUNT;
   result["FUTUREPIA_FPCH_INTEREST_COMPOUND_INTERVAL_SEC"] = FUTUREPIA_FPCH_INTEREST_COMPOUND_INTERVAL_SEC;
   result["FUTUREPIA_SECONDS_PER_YEAR"] = FUTUREPIA_SECONDS_PER_YEAR;
   result["FUTUREPIA_RECENT_RSHARES_DECAY_RATE_HF19"] = FUTUREPIA_RECENT_RSHARES_DECAY_RATE_HF19;
   result["FUTUREPIA_RECENT_RSHARES_DECAY_RATE_HF17"] = FUTUREPIA_RECENT_RSHARES_DECAY_RATE_HF17;
   result["FUTUREPIA_REVERSE_AUCTION_WINDOW_SECONDS"] = FUTUREPIA_REVERSE_AUCTION_WINDOW_SECONDS;
   result["FUTUREPIA_ROOT_POST_PARENT"] = FUTUREPIA_ROOT_POST_PARENT;
   result["FUTUREPIA_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = FUTUREPIA_SAVINGS_WITHDRAW_REQUEST_LIMIT;
   result["FUTUREPIA_SAVINGS_WITHDRAW_TIME"] = FUTUREPIA_SAVINGS_WITHDRAW_TIME;
   result["FUTUREPIA_FPCH_START_PERCENT"] = FUTUREPIA_FPCH_START_PERCENT;
   result["FUTUREPIA_FPCH_STOP_PERCENT"] = FUTUREPIA_FPCH_STOP_PERCENT;
   result["FUTUREPIA_SOFT_MAX_COMMENT_DEPTH"] = FUTUREPIA_SOFT_MAX_COMMENT_DEPTH;
   result["FUTUREPIA_START_MINER_VOTING_BLOCK"] = FUTUREPIA_START_MINER_VOTING_BLOCK;
   result["FUTUREPIA_SYMBOL"] = FUTUREPIA_SYMBOL;
   result["FUTUREPIA_TEMP_ACCOUNT"] = FUTUREPIA_TEMP_ACCOUNT;
   result["FUTUREPIA_UPVOTE_LOCKOUT_HF7"] = FUTUREPIA_UPVOTE_LOCKOUT_HF7;
   result["FUTUREPIA_UPVOTE_LOCKOUT_HF17"] = FUTUREPIA_UPVOTE_LOCKOUT_HF17;
   result["FUTUREPIA_VOTE_CHANGE_LOCKOUT_PERIOD"] = FUTUREPIA_VOTE_CHANGE_LOCKOUT_PERIOD;
   result["FUTUREPIA_VOTE_DUST_THRESHOLD"] = FUTUREPIA_VOTE_DUST_THRESHOLD;
   result["FUTUREPIA_VOTE_REGENERATION_SECONDS"] = FUTUREPIA_VOTE_REGENERATION_SECONDS;
   result["VIRTUAL_SCHEDULE_LAP_LENGTH"] = VIRTUAL_SCHEDULE_LAP_LENGTH;
   result["VIRTUAL_SCHEDULE_LAP_LENGTH2"] = VIRTUAL_SCHEDULE_LAP_LENGTH2;

   return result;
}

} } // futurepia::protocol
